feat(init): gallery
hackclub/riceathon pull request #79
Opened 2024-12-31 06:20 UTC by NeonGamerBot-QK

Riceathon gallery :D 
cc @OtterCodes101

2024-12-31 15:40 UTC, DaInfLoop commented on docs/gallery/index.html
> +    document.getElementById('headline').innerText = `Gallery of the ${gallery.length + 1} rice's`
This shouldn't be `gallery.length + 1` since that means (at the time of review) 51 rices makes this header say "52 rice's".

Also, grammatically it should be "rices", not "rice's".

2024-12-31 15:40 UTC, DaInfLoop commented on docs/gallery/index.html
> +  const data = await fetch(
Pet peeve, sure, but don't fetch this twice, even if they're fetched in different contexts: that wastes requests. Fetch it in one place (near the bottom somewhere) and then pass the JSON response to these functions.

2024-12-31 15:40 UTC, DaInfLoop commented on docs/gallery/index.html
> +    h1.innerText = cold.name
There's not a big enough gap between the username and the image that I can't tell that it's clickable after the links load.

![image](https://github.com/user-attachments/assets/8b9b37d1-d2f8-4cb5-ae38-1f1b03c80546)

Also maybe add a transition to the hover effect so it's not instant. Again, another pet peeve.

2024-12-31 15:43 UTC, DaInfLoop commented on docs/gallery/index.html
> +    h1.innerText = cold.name
> There's not a big enough gap between the username and the image that I can't tell that it's clickable after the links load.
On the official [theme page](https://theme.hackclub.com/), there's an "interactive card" which is the exact same as the primary card except it has a hover animation where it gets bigger. Maybe you could use that instead of the underline becoming squiggly?

2025-01-01 01:21 UTC, DaInfLoop reviewed
I completely forgot to review the actual rice view page :sob: 

The gallery view looks better though.

2025-01-01 01:21 UTC, DaInfLoop commented on docs/gallery/index.html
> +  }
Having a bit more of a look at the carousel on the actual view page, it's confusing as to what it is.

When I saw the buttons on some pages but others, I thought this was some bug as to "why does the previous and next buttons not show on some pages?"

It's not really clear that these are for an image carousel: I initially thought they were for moving between the different rices.

2025-01-01 01:21 UTC, DaInfLoop commented on docs/gallery/icon.js
> +  icon.style.height = "40px";
Force a width only, not a height (or force a height and not a width). The NixOS icon here looks squished because it's forced to `40x40`.
![image](https://github.com/user-attachments/assets/e709c6f3-236f-458c-823b-ed1e287e1fe3)

2025-01-01 01:21 UTC, DaInfLoop commented on docs/gallery/index.html
> +    h1.appendChild(setupIcon(data.distro))
Another pet peeve: the text and the image aren't aligned properly.
![image](https://github.com/user-attachments/assets/e709c6f3-236f-458c-823b-ed1e287e1fe3)

You _could_ probably fix this with `vertical-align` on the image or flexbox.

2025-01-01 01:21 UTC, DaInfLoop commented on docs/gallery/index.html
> +    h1.appendChild(setupIcon(data.distro))
It's unsure as to what the distro icon actually means in this context to be honest. Might just be me.

Maybe add a different label somewhere on the page, like:

```
                USER
    View dotfiles • [X] DISTRO
```

2025-01-01 01:26 UTC, NeonGamerBot-QK commented on docs/gallery/index.html
> +    h1.appendChild(setupIcon(data.distro))
the distro image is next to the dotfiles link to show what OS the dotfiles are for.

2025-01-01 06:48 UTC, NeonGamerBot-QK commented on docs/gallery/index.html
> +  }
ah sorry, i have fixed them to be clearer

2025-01-01 15:58 UTC, DaInfLoop requested changes
Just one small fix from the second review I did. Except for that, LGTM

2025-01-01 15:58 UTC, DaInfLoop commented on docs/gallery/index.html
> +    h1.appendChild(setupIcon(data.distro))
Still feels a bit off-centered. I ended up fixing this on my local copy with making it a flexbox container:

- Making the container a `div`
- Aligning horizontally with `justify-content: center;`
- Aligning vertically with `align-items: center;`
- Adding the gap between the items with `gap` (I used `var(--spacing-2)` which is 8px).
- Creating the `<h1>` effect with `font-size: var(--font-5); font-weight: var(--font-weight-bold);`

```suggestion
  const titleThing = document.createElement('div')
  titleThing.innerText = data.name
  const div = titleThing
  div.style.display = "flex"
  div.style.justifyContent = "center"
  div.style.alignItems = "center"
  div.style.gap = "var(--spacing-2)"
  div.style.fontSize = "var(--font-5)"
  div.style.fontWeight = "var(--font-weight-bold)"
  
  const gitLink = document.createElement('a')
  gitLink.href = data.git
  gitLink.innerText = "Dotfiles"
  gitLink.style.textDecoration = "none"
  gitLink.target = "_blank"
  
    div.appendChild(document.createTextNode(" - "))
    div.appendChild(gitLink)
    div.appendChild(setupIcon(data.distro))
```

2025-01-01 20:09 UTC, DaInfLoop approved these changes
LGTM :+1:

2025-01-01 20:44 UTC, merged